let modelsApadrinheJson = [
    {
        "id": 1,
        "name": "Pretinho",
        "description": "Minha história começou em um lar onde me maltratavam e me deixavam dias sem comer. Por sorte a ONG me encontrou e me resgatou. Infelizmente, tenho uma doença crônica e por conta disso está difícil encontrar uma família que consiga cuidar de mim.",
        "img": "./images/dog7.jpeg",
        "title": "Custos mensais do Pretinho",
        "account": "Cálculo baseado em um mês normal com consultas, vacinas e acompanhamento usual. Mesmo que hajam gastos emergenciais eles não serão adicionados além da ajuda mensal.",
        "value": "<br> Ração: R$ 120,00/mês <br> Banho: R$ 45,00/mês <br> Vacina: R$ 6,70/mês <br> Antipulgas: R$ 120,00/mês <br> Adestramento: R$ 200,00/mês",
    },
    {
        "id": 2,
        "name": "Pitica",
        "description": "Oi! Eu sou uma ovelha muito fofa e brincalhona! Fui encontrada pela ONG em situação de risco, e agora tenho um lar em uma fazenda! Acompanhe minha história. <3",
        "img": "./images/ovelha1.jpg",   
        "title": "Custos mensais da Pitica",
        "account": "Cálculo baseado em um mês normal com consultas, vacinas e acompanhamento usual. Mesmo que hajam gastos emergenciais eles não serão adicionados além da ajuda mensal.",
        "value": "<br> Ração: R$ 120,00/mês <br> Banho: R$ 45,00/mês <br> Vacina: R$ 6,70/mês <br> Antipulgas: R$ 120,00/mês <br> Adestramento: R$ 200,00/mês",
    },
    {
        "id": 3,
        "name": "Fifi",
        "description": "Sou a Fifi, a gatinha mais manhenta que você vai conhecer! Eu estou passando por um momento muito difícil, por isso preciso de ajuda para realizar meus exames e vacinas! Me ajude a ter um futuro.",
        "img": "./images/cat5.jpg",
        "title": "Custos mensais da Fifi",
        "account": "Cálculo baseado em um mês normal com consultas, vacinas e acompanhamento usual. Mesmo que hajam gastos emergenciais eles não serão adicionados além da ajuda mensal.",
        "value": "<br> Ração: R$ 120,00/mês <br> Banho: R$ 45,00/mês <br> Vacina: R$ 6,70/mês <br> Antipulgas: R$ 120,00/mês <br> Adestramento: R$ 200,00/mês",
    },
    {
        "id": 4,
        "name": "Juninho play",
        "description": "Nasci na rua, por sorte a ONG me encontrou logo que nasci! Minha mamãe morreu junto com a ninhada de 4 filhotes, eu fui o único que sobreviveu.",
        "img": "./images/dog8.jpg",
        "title": "Custos mensais do Juninho play",
        "account": "Cálculo baseado em um mês normal com consultas, vacinas e acompanhamento usual. Mesmo que hajam gastos emergenciais eles não serão adicionados além da ajuda mensal.",
        "value": "<br> Ração: R$ 120,00/mês <br> Banho: R$ 45,00/mês <br> Vacina: R$ 6,70/mês <br> Antipulgas: R$ 120,00/mês <br> Adestramento: R$ 200,00/mês",
    },
    {
        "id": 5,
        "name": "Biscoito",
        "description": "Eu fui abandonado, me ajude a ter um futuro melhor",
        "img": "./images/cat6.jpg",
        "title": "Custos mensais do Biscoito",
        "account": "Cálculo baseado em um mês normal com consultas, vacinas e acompanhamento usual. Mesmo que hajam gastos emergenciais eles não serão adicionados além da ajuda mensal.",
        "value": "<br> Ração: R$ 120,00/mês <br> Banho: R$ 45,00/mês <br> Vacina: R$ 6,70/mês <br> Antipulgas: R$ 120,00/mês <br> Adestramento: R$ 200,00/mês",
    },
    {
        "id": 6,
        "name": "Cacau",
        "description": "Meus papais não sobreviveram a um acidente de carro, agora, a ONG cuida de mim!",
        "img": "./images/cat7.jpg",
        "title": "Custos mensais da Cacau",
        "account": "Cálculo baseado em um mês normal com consultas, vacinas e acompanhamento usual. Mesmo que hajam gastos emergenciais eles não serão adicionados além da ajuda mensal.",
        "value": "<br> Ração: R$ 120,00/mês <br> Banho: R$ 45,00/mês <br> Vacina: R$ 6,70/mês <br> Antipulgas: R$ 120,00/mês <br> Adestramento: R$ 200,00/mês",
    }
];